name = "PromptForm"
client_id = "352e9deba81fac32cb0727b95d682158"
application_url = "https://promptform.mesh99.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bigdatashopgpttest.myshopify.com"

[access_scopes]
scopes = "read_products,write_products,read_orders"

[auth]
redirect_urls = [
    "https://promptform.mesh99.com/authenticate",
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app/uninstalled"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://promptform.mesh99.com/api/webhooks/gdpr/customers-data-request"
  customer_deletion_url = "https://promptform.mesh99.com/api/webhooks/gdpr/customers-redact"
  shop_deletion_url = "https://promptform.mesh99.com/api/webhooks/gdpr/shop-redact"
