# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "352e9deba81fac32cb0727b95d682158"
name = "PromptForm"
application_url = "https://promptform.mesh99.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bigdatashopgpttest.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/gdpr/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/gdpr/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/gdpr/shop-redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://promptform.mesh99.com/authenticate" ]
